server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [

    # Path for the about view
    path('about/', view=views.about, name='about'),

    # Path for the contact us view
    path('contact/', view=views.contact, name='contact'),

    # Path for registration
    path('registration/', view=views.registration_request, name='registration'),

    # Path for login
    path('login/', view=views.login_request, name='login'),

    # Path for logout
    path('logout/', view=views.logout_request, name='logout'),

    # Path for index
    path('', view=views.get_dealerships, name='index'),

    # Path for dealer reviews view
    path('dealer/<int:id>/', views.get_dealer_details, name='dealer_details'),

    # Path for add a review view
    path('dealer/review/<int:id>/', views.add_review, name='add_review'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
import json
from django.db import models

class TestModel(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class CarMake(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.name

class CarModel(models.Model):
    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    dealer_id = models.IntegerField()
    
    TYPE_CHOICES = [
        ('SEDAN', 'Sedan'), 
        ('SUV', 'SUV'),
        ('WAGON', 'Wagon'),
    ]
    
    YEAR_CHOICES = [(year, year) for year in range(1950, 2024)]
    
    type_car = models.CharField(max_length=50, choices=TYPE_CHOICES, default='SEDAN')
    year = models.IntegerField(choices=YEAR_CHOICES)

    def __str__(self):
        return self.name

class CarDealer:
    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return f"{self.full_name}, {self.st}"

class DealerReview:
    def __init__(self, dealership, name, purchase, review):
        # Required attributes
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        # Optional attributes
        self.purchase_date = ""
        self.purchase_make = ""
        self.purchase_model = ""
        self.purchase_year = ""
        self.sentiment = ""
        self.id = ""

    def __str__(self):
        return "Review: " + self.review

    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__,
                          sort_keys=True, indent=4)

class ReviewPost:
    def __init__(self, dealership, name, purchase, review):
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        self.purchase_date = ""
        self.car_make = ""
        self.car_model = ""
        self.car_year = ""

    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__,
                            sort_keys=True, indent=4)

server/djangoapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import CarDealer, CarMake, CarModel, DealerReview, ReviewPost
from .restapis import (
    get_dealers_from_cf,
    get_request,
    get_dealer_by_id_from_cf,
    get_dealer_reviews_from_cf,
    post_request,
    analyze_review_sentiments
)
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime
import logging


# Get an instance of a logger
logger = logging.getLogger(__name__)

# Views

def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)

def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)

def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('djangoapp:index')
 
        else:
            context['message'] = "Invalid username or password"
            return render(request, 'djangoapp/index.html', context)
    else:
        return render(request, 'djangoapp/index.html', context)

def logout_request(request):
    if request.method == "GET":
        print("Logging out the user '{}'".format(request.user.username))
        logout(request)
    return redirect('djangoapp:index')

def registration_request(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except User.DoesNotExist:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, password=password)
            user.is_superuser = True
            user.is_staff = True
            user.save()
            login(request, user)
            return redirect("djangoapp:index")
        else:
            messages.warning(request, "The user already exists.")
            return redirect('djangoapp:registration')

def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "https://eu-de.functions.appdomain.cloud/api/v1/web/98f9f7ac-eac8-4b14-8a1b-f707b7642a8b/dealership-package/get-dealership"
        dealerships = get_dealers_from_cf(url)
        context["dealership_list"] = dealerships
        return render(request, 'djangoapp/index.html', context)

def get_dealer_details(request, id):
    if request.method == "GET":
        context = {}
        dealer_url = "https://eu-de.functions.appdomain.cloud/api/v1/web/98f9f7ac-eac8-4b14-8a1b-f707b7642a8b/dealership-package/get-dealership"
        dealer = get_dealer_by_id_from_cf(dealer_url, id=id)
        context["dealer"] = dealer

        review_url = "https://eu-de.functions.appdomain.cloud/api/v1/web/98f9f7ac-eac8-4b14-8a1b-f707b7642a8b/dealership-package/get-review"
        reviews = get_dealer_reviews_from_cf(review_url, id=id)
        context["reviews"] = reviews
        return render(request, 'djangoapp/dealer_details.html', context)

@login_required
def add_review(request, id):
    context = {}
    dealer_url = "https://eu-de.functions.appdomain.cloud/api/v1/web/98f9f7ac-eac8-4b14-8a1b-f707b7642a8b/dealership-package/get-dealership"
    dealer = get_dealer_by_id_from_cf(dealer_url, id=id)
    context["dealer"] = dealer

    if request.method == 'GET':
        # Get cars for the dealer
        cars = CarModel.objects.all()
        context["cars"] = cars
        return render(request, 'djangoapp/add_review.html', context)
    elif request.method == 'POST':
        if request.user.is_authenticated:
            username = request.user.username
            payload = dict()
            car_id = request.POST["car"]
            car = CarModel.objects.get(pk=car_id)
            payload["time"] = datetime.utcnow().isoformat()
            payload["name"] = username
            payload["dealership"] = id
            payload["id"] = id
            payload["review"] = request.POST["content"]
            payload["purchase"] = False
            if "purchasecheck" in request.POST:
                if request.POST["purchasecheck"] == 'on':
                    payload["purchase"] = True
            payload["purchase_date"] = request.POST["purchasedate"]
            payload["car_make"] = car.car_make.name
            payload["car_model"] = car.name
            payload["car_year"] = car.year
            new_payload = {"review": payload}
            review_post_url = "https://eu-de.functions.appdomain.cloud/api/v1/web/98f9f7ac-eac8-4b14-8a1b-f707b7642a8b/dealership-package/post-review"
            post_request(review_post_url, new_payload, id=id)
        return redirect("djangoapp:dealer_details", id=id)

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/djangoapp">Best Cars</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/djangoapp">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/djangoapp/about">About Page</a>
                </li>
                <li class="nav-item">
                    <a class= "nav-link" href="/djangoapp/contact">Contact Us</a>
                </li>
            </ul>
        </div>
    </nav>
    <p>Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.</p>
</body>
</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
</head>
<body>
<div class="container-fluid">
    <h3>Please add a review for <b>{{ dealer.full_name }}</b></h3>
    <form action="{% url 'djangoapp:add_review' dealer.id %}" method="post">
        <div class="form-group">
            <label for="content"><b>Enter the review content:</b></label>
            <textarea class="form-control" id="content" name="content" rows="2" required></textarea>
        </div>

        <div class="form-group form-check">
            <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
            <label for="purchasecheck">Has purchased the car from {{ dealer.full_name }}?</label>
            <label class="text-muted">(Select purchased car information below if checked)</label>
        </div>

        <div class="form-group">
            <label for="car"><b>Select your car (model-car_make-year):</b></label>
            <select name="car" id="car" class="form-select" required>
                {% for car in cars %}
                    <option selected value="{{ car.id }}">{{ car.name }}-{{ car.car_make.name }}-{{ car.year }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="purchasedate"><b>Select Your Purchase Date (mm/dd/yyyy):</b></label>
            <input class="date-own form-control" style="width: 200px;" type="text" name="purchasedate" id="purchasedate">
        </div>

        {% csrf_token %}
        <div>
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </form>
</div>

<script type="text/javascript">
    // Initialize the date picker
    $('#purchasedate').datepicker({
        format: 'mm/dd/yyyy'
    });
</script>
</body>
</html>

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/djangoapp">Best Cars</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/djangoapp">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/djangoapp/about">About Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/djangoapp/contact">Contact Us</a>
                </li>
            </ul>
        </div>
    </nav>
    <p>Welcome to Best Cars Contact Page</p>
    <p>Address: House #, Street Name, Postal Code, Country</p>
    <p>Phone Number: 1234-0-000-0000-0000</p>
</body>
</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body> 

    <!-- Nav Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/djangoapp">Best Cars</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/djangoapp">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/djangoapp/about">About Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/djangoapp/contact">Contact Us</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'djangoapp:add_review' dealer.id %}">Add Review</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ user.first_name }} ({{ user.username }})</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <form class="form-inline my-2 my-lg-0" action="#" method="post">
                            {% csrf_token %}
                            <input type="text" class="form-control mr-sm-2" placeholder="Username" name="username">
                            <input type="password" class="form-control mr-sm-2" placeholder="Password" name="psw">
                            <button class="btn btn-success my-2 my-sm-0" type="submit">Login</button>
                        </form>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary my-2 my-sm-0" href="/djangoapp/registration">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Reviews Cards -->
    <div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <h3>Reviews for <b>{{ dealer.full_name }}</b></h3>

        <div class="container">
            <div class="card-columns">
                {% for review in reviews %}
                <div class="col-auto mb-3">
                    <div class="card">
                        {% if review.sentiment == "positive" %}
                            <img class="card-img-left" src="{{ MEDIA_URL }}/emoji/positive.png" width="36px" height="36px" alt="Sentiment">
                        {% elif review.sentiment == "negative" %}
                            <img class="card-img-left" src="{{ MEDIA_URL }}/emoji/negative.png" width="36px" height="36px" alt="Sentiment">
                        {% else %}
                            <img class="card-img-left" src="{{ MEDIA_URL }}/emoji/neutral.png" width="36px" height="36px" alt="Sentiment">
                        {% endif %}
                        <div class="card-body bg-light">
                            {% if review.car_make %}
                                <h5 class="card-title">{{ review.car_make }}, {{ review.car_model }}</h5>
                                <h5 class="card-title">{{ review.car_year }}</h5>
                            {% endif %}
                            <p class="card-text">{{ review.review }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <style>
        .dealer-link {
            transition: transform 0.3s, background-color 0.3s;
            display: inline-block;
            text-decoration: none;
            padding: 5px 10px;
            border-radius: 5px;
            font-size: 16px;
        }

        .dealer-link:hover {
            transform: scale(1.05);
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            background-color: #f8f9fa;
        }
    </style>
</head>

<body> 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/djangoapp">Best Cars</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/djangoapp">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/djangoapp/about">About Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/djangoapp/contact">Contact Us</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="#">{{ user.first_name }} ({{ user.username }})</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary my-2 my-sm-0" href="{% url 'djangoapp:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <div id="login-form"></div>
                            <form class="form-inline my-2 my-lg-0" action="{% url 'djangoapp:login' %}" method="post">
                                {% csrf_token %}
                                <input type="text" class="form-control mr-sm-2" placeholder="Username" name="username" required>
                                <input type="password" class="form-control mr-sm-2" placeholder="Password" name="psw" required>
                                <button class="btn btn-success my-2 my-sm-0" type="submit" data-toggle="modal" data-target="#loginErrorModal">Login</button>
                            </form>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary my-2 my-sm-0" href="/djangoapp/registration">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Add a dealer table here -->
    <table class="table" id="table" data-filter-control="true">
        <thead>
            <tr>
                <th data-field="id">ID</th>
                <th data-field="dealer_names">Dealer Name</th>
                <th data-field="city">City</th>
                <th data-field="address">Address</th>
                <th data-field="zip">Zip</th>
                <th data-field="state" data-filter-control="select">State</th>                                        
            </tr>
        </thead>
        <tbody>
            {% for dealer in dealership_list %}
                <tr>
                    <td>{{ dealer.id }}</td>
                    <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}" class="dealer-link" style="color: #007BFF">{{ dealer.full_name }}</a></td>
                    <td>{{ dealer.city }}</td>
                    <td>{{ dealer.address }}</td>
                    <td>{{ dealer.zip }}</td>
                    <td>{{ dealer.st }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <!-- Turn on filter control for the table -->
    <script>
        $(function(){
            $('#table').bootstrapTable()
        })
    </script>

    <!-- Java display error modal if login fields empty -->
    <script>
        $(document).ready(function() {
            $('#login-form button[type="submit"]').click(function(event) {
                var username = $('input[name="username"]').val();
                var password = $('input[name="psw"]').val();
                if (username === '' || password === '') {
                    event.preventDefault(); // Prevent form submission
                    $('#loginErrorModal').modal('show');
                }
            });
        });
    </script>

    <!-- Bootstrap modal for login error message -->
    <div class="modal fade" id="loginErrorModal" tabindex="-1" role="dialog" aria-labelledby="loginErrorModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginErrorModalLabel">Error</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Invalid username or password. Please fill in the login fields.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <form action="{% url 'djangoapp:registration' %}" method="post">
        <div class="container">
            {% csrf_token %}
            <h1>Sign Up</h1>
            <hr>

            <div class="form-group">
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Enter User Name" name="username" required>

                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter First Name" name="firstname" required>

                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name" name="lastname" required>

                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Enter Password" name="psw" required>

                {% if message %}
                <div class="alert-warning">
                    {{ message }}
                </div>
                {% endif %}

                <br>
                <button class="btn btn-primary" type="submit">Sign Up</button>
            </div>
        </div>
    </form>
</body>
</html>